[
   "$100 OG",
                                              "3 Kings",
                                              "707 Headband",
                                              "A-10",
                                              "A-Train",
                                              "Acapulco Gold",
                                              "Ace of Spades",
                                              "Afghan Big Bud",
                                              "Afghan Diesel",
                                              "Afghan Kush",
                                              "Afghan skunk",
                                              "Afghani",
                                              "Afghani Bullrider",
                                              "Afghanica",
                                              "Afghooey",
                                              "Afgoo",
                                              "Afgooey",
                                              "Afwreck",
                                              "Agent Orange",
                                              "AK-47",
                                              "AK-48",
                                              "Alaskan Thunder Fuck",
                                              "Albert Walker",
                                              "Alien Dawg",
                                              "Alien Kush",
                                              "Alien OG",
                                              "Allen Wrench",
                                              "Aloha",
                                              "Alohaberry",
                                              "Ambrosia",
                                              "Amethyst",
                                              "Amnesia",
                                              "Amnesia Haze",
                                              "Anesthesia",
                                              "Animal Cookies",
                                              "Apollo 11",
                                              "Apollo 13",
                                              "Arabian Gold",
                                              "Arjan\u0027s Strawberry Haze",
                                              "Armageddon",
                                              "Asian Fantasy",
                                              "Atomic Northern Lights",
                                              "Avalon",
                                              "Banana Candy",
                                              "Banana Diesel",
                                              "Banana Kush",
                                              "Banana OG",
                                              "BC Big Bud",
                                              "BC Roadkill",
                                              "BC Sweet Tooth",
                                  "Belladonna",
                                              "Berkeley",
                                              "Berry White",
                                              "Big Bud",
                                              "Big Buddha Cheese",
                                              "Big Wreck",
                                              "Bio-Diesel",
                                              "Bio-Jesus",
                                              "Black Cherry Soda",
                                              "Black Dahlia",
                                              "Black Diamond",
                                              "Black Diesel",
                                              "Black Domina",
                                              "Black Ice",
                                              "Black Jack",
                                              "Black Label Kush",
                                              "Black Mamba",
                                              "Black Tuna",
                                              "Black Velvet",
                                              "Black Widow",
                                              "Blackberry",
                                              "Blackberry Hashplant",
                                              "Blackberry Kush",
                                              "Blockhead",
                                              "Blue Bastard",
                                              "Blue Bayou",
                                              "Blue Boy",
                                              "Blue Champagne",
                                              "Blue Cheese",
                                              "Blue Crack",
                                              "Blue Diesel",
                                              "Blue Dragon",
                                              "Blue Dream",
                                              "Blue Goo",
                                              "Blue Hawaiian",
                                              "Blue Haze",
                                              "Blue Ivy",
                                              "Blue Lights",
                                              "Blue Magoo",
                                              "Blue Moonshine",
                                              "Blue Mystic",
                                              "Blue OG",
                                              "Blue Rhino",
                                              "Blue Satellite",
                                              "Blue Train",
                                              "Blue Widow",
                                              "Blueberry",
                                              "Blueberry Cheesecake",
                                              "Blueberry Diesel",
                                              "Blueberry Haze",
                                              "Blueberry Headband",
                                              "Blueberry Kush",
                                              "Blueberry x Hash Plant",
                                              "Boggle Gum",
                                              "Bordello",
                                              "Boysenberry ",
                                              "Brainstorm Haze",
                                              "Broke Diesel",
                                              "Bruce Banner",
                                              "Bruce Banner #3",
                                              "Bubba Kush",
                                              "Bubba OG",
                                              "Bubble Gum",
                                              "Bubbleberry",
                                              "Bubblegun",
                                              "Buddha\u0027s Sister",
                                              "Burmese Kush",
                                              "Butterscotch",
                                              "C13 Haze",
                                              "Cadillac Purple",
                                              "Cali Gold",
                                              "Cali Kush",
                                              "California Orange",
                                              "Candy Jack",
                                              "Cannadential",
                                              "Cannalope Haze",
                                              "Cannatonic",
                                              "Caramelicious",
                                              "Casey Jones",
                                              "Cat Piss",
                                              "Cataract Kush",
                                              "Champagne Kush",
                                              "Charlotte\u0027s Web",
                                              "Cheese",
                                              "Cheese Quake",
                                              "Chemdawg",
                                              "Chemdawg 4",
                                              "Chernobyl",
                                              "Cherry AK-47",
                                              "Cherry Bomb",
                                              "Cherry Kush",
                                              "Cherry Pie",
                                              "Chiesel",
                                              "Chocolate Chunk",
                                              "Chocolate Kush",
                                              "Chocolope",
                                              "Church OG",
                                              "Cinderella 99",
                                              "Cinex",
                                              "Citrus Kush",
                                              "Cold Creek Kush",
                                              "Confidential Cheese",
                                              "Connie Chung",
                                              "Corleone Kush",
                                              "Cotton Candy Kush",
                                              "Cracker Jack",
                                              "Crimea Blue",
                                              "Critical Mass",
                                              "Dairy Queen",
                                              "Danky Doodle",
                                              "Dark Star",
                                              "Darth Vader OG",
                                              "Deadhead OG",
                                              "Death Star",
                                              "Deathstar OG",
                                              "Deep Purple",
                                              "Diablo",
                                              "Diamond OG",
                                              "Diesel Duff",
                                              "Dixie Dew Drops",
                                              "Dixie Elixirs Lemonade",
                                              "Dixie Elixirs Mixed Berry",
                                              "Dixie Elixirs Old-Fashioned Sarsaparilla",
                                              "Dixie Elixirs Peach",
                                              "Dixie Elixirs Pomegranate",
                                              "Dixie Elixirs Sparkling Blueberry",
                                              "Dixie Elixirs Sparkling Grapefruit",
                                              "Dixie Elixirs Sparkling Mandarin",
                                              "Dixie Elixirs Sparkling Red Currant",
                                              "Dixie Elixirs Sweet Tea",
                                              "Dixie Med-a-Mints",
                                              "Dixie Medicated Chocolate Truffles",
                                              "Dixie Medicated Crispy Rice Treats",
                                              "Dixie Medicated Fruit Lozenges",
                                              "Dixie Scrips A.M. Focus",
                                              "Dixie Scrips General Pain Relief",
                                              "Dixie Scrips P.M. Sleep",
                                              "Dixie\u0027s Colorado Bar",
                                              "DJ Short Blueberry",
                                              "Django",
                                              "Domino",
                                              "Dopium",
                                              "Double Diesel",
                                              "Dream Queen",
                                              "Duke Nukem",
                                              "Durban Cheese",
                                              "Durban Poison",
                                              "Dutch Dragon",
                                              "Dutch Hawaiian",
                                              "Dutch Treat",
                                              "Dynamite",
                                              "Early Girl",
                                              "Earthquake",
                                              "East Coast Sour Diesel",
                                              "Ed Rosenthal Super Bud",
                                              "Edelweiss",
                                              "El Jeffe",
                                              "El Nino",
                                              "Euphoria",
                                              "Ewok",
                                              "Exodus Cheese",
                                              "Fire Haze",
                                              "Fire OG",
                                              "Flo",
                                              "Freezeland",
                                              "Frostbite",
                                              "Frosty",
                                              "Fruity Pebbles",
                                              "Fucking Incredible",
                                              "Funky Monkey",
                                              "G Stik \"Amarillo\"",
                                              "G Stik \"Orange\"",
                                              "G Stik \"RED\"",
                                              "G Stik \"Rosado\"",
                                              "G Stik \"Verde\"",
                                              "G Stik \"Violeta\"",
                                              "G13",
                                              "G13 Haze",
                                              "Ghost OG",
                                              "Girl Scout Cookies",
                                              "Glass Slipper",
                                              "God Bud",
                                              "God\u0027s Gift",
                                              "Godberry",
                                              "Godfather OG",
                                              "Goldberry",
                                              "Golden Goat",
                                              "Goldwing",
                                              "Grand Hindu",
                                              "Grand Hustle",
                                              "Granddaddy Purple",
                                              "Grape Ape",
                                              "Grape Crush",
                                              "Grape God",
                                              "Grape Krush",
                                              "Grape Kush",
                                              "Grape Skunk",
                                              "Grapefruit",
                                              "Grapefruit Diesel",
                                              "Grapefruit Haze",
                                              "Grapefruit Kush",
                                              "Gravity",
                                              "Green Candy",
                                              "Green Crack",
                                              "Green Crack Extreme",
                                              "Green Door Kush",
                                              "Green Dream",
                                              "Green Goblin",
                                              "Green Haze",
                                              "Green Hornet",
                                              "Green Kush",
                                              "Green Monster",
                                              "Green Queen",
                                              "Green Ribbon",
                                              "Guido Kush",
                                              "Gumbo",
                                              "Harlequin",
                                              "Hash Plant",
                                              "Hashberry",
                                              "Hashplant Haze",
                                              "Hawaiian",
                                              "Hawaiian Delight",
                                              "Hawaiian Diesel",
                                              "Hawaiian Fire",
                                              "Hawaiian Haze",
                                              "Hawaiian Punch",
                                              "Hawaiian Sativa",
                                              "Hawaiian Skunk",
                                              "Hawaiian Snow",
                                              "Hawaiian Thunder Fuck",
                                              "Haze",
                                              "Headband",
                                              "Headbanger",
                                              "Heavy Duty Fruity",
                                              "Hempstar",
                                              "Herojuana",
                                              "Himalayan Gold",
                                              "Hindu Kush",
                                              "Hindu Skunk",
                                              "Hippie Crippler",
                                              "Hog",
                                              "Hog\u0027s Breath",
                                              "Hollands Hope",
                                              "Holy Grail Kush",
                                              "Hong Kong",
                                              "Huckleberry",
                                              "Humboldt",
                                              "Hydro Green Crack",
                                              "Ice",
                                              "Ice Cream",
                                              "Ingrid",
                                              "Island Sweet Skunk",
                                              "J-27",
                                              "J1",
                                              "Jack Flash",
                                              "Jack Frost",
                                              "Jack Haze",
                                              "Jack Herer",
                                              "Jack Kush",
                                              "Jack the Ripper",
                                              "Jack Widow",
                                              "Jack\u0027s Cleaner",
                                              "Jagermeister",
                                              "Jah Kush",
                                              "Jamaican Pearl",
                                              "Jane Doe",
                                              "Jean Guy",
                                              "Jesus OG",
                                              "Jillybean",
                                              "Juicy Fruit",
                                              "Julius Caesar",
                                              "Jupiter Kush",
                                              "Jupiter OG",
                                              "K Train",
                                              "Kaboom",
                                              "Kahuna",
                                              "Kali Mist",
                                              "Kandy Kush",
                                              "Key Lime Haze",
                                              "Khola",
                                              "Killer Queen",
                                              "Killing Fields",
                                              "King Kong",
                                              "King Kush",
                                              "King Louis",
                                              "King\u0027s Bread",
                                              "Kosher Kush",
                                              "Kryptonite",
                                              "Kush Berry",
                                              "Kushage",
                                              "Kushberry",
                                              "LA Confidential",
                                              "LA Jack",
                                              "LA OG",
                                  "LA Woman",
                                              "Lamb\u0027s Bread",
                                              "Lambo OG",
                                              "Larry OG",
                                              "Laughing Buddha",
                                              "Lavender",
                                              "Lavender Haze",
                                              "Lavender Kush",
                                              "Lemon Diesel",
                                              "Lemon Drop",
                                              "Lemon G",
                                              "Lemon Haze",
                                              "Lemon Jack",
                                              "Lemon Kush",
                                              "Lemon OG",
                                              "Lemon Sativa",
                                              "Lemon Skunk",
                                              "Lemon Thai",
                                              "Lemon Wreck",
                                              "Liberty Haze",
                                              "Lifesaver",
                                              "Lime Green Skunk",
                                              "Lions Gate",
                                              "Liquid Butter",
                                              "Louis XIII",
                                              "LSD",
                                              "LVPK",
                                              "M-39",
                                              "Mad Dawg",
                                              "Madagascar",
                                              "Mako Haze",
                                              "Malawi",
                                              "Mango",
                                              "Mango Dream",
                                              "Mango Kush",
                                              "Maple Leaf Indica",
                                              "Mars OG",
                                              "Martian Mean Green",
                                              "Master Bubba",
                                              "Master Jedi",
                                              "Master Kush",
                                              "Master Yoda",
                                              "Matanuska Thunder Fuck",
                                              "Matsu",
                                              "Maui",
                                              "Maui Berry",
                                              "Maui Waui",
                                              "Mazar I Sharif",
                                              "Medicated Dixie Roll",
                                              "Medicine Man",
                                              "Mendocino Purps",
                                              "Mercury OG",
                                              "Mexican Sativa",
                                              "Millennium",
                                              "Misty Kush",
                                              "MK Ultra",
                                              "Moby Dick",
                                              "Morning Star",
                                              "Mr. Nice",
                                              "Nebula",
                                              "Neptune Kush",
                                              "Neptune OG",
                                              "Neville\u0027s Haze",
                                              "Northern Lights",
                                              "Northern Lights #5",
                                              "Northern Skunk",
                                              "Nuggetry OG",
                                              "NYC Diesel",
                                              "Obama Kush",
                                              "OCD",
                                              "Odyssey",
                                              "OG",
                                              "OG Diesel Kush",
                                              "OG Kush",
                                              "OG Poison",
                                              "OG Wreck",
                                              "OGiesel",
                                              "Ogre",
                                              "Old Lyme Connecticut OG",
                                              "Orange Bud",
                                              "Orange Crush",
                                              "Orange Dream",
                                              "Orange Kush",
                                              "Orange Velvet",
                                              "Organic Diesel",
                                              "Outer Space",
                                              "P-91",
                                              "Panama Red",
                                              "Pandora\u0027s Box",
                                              "Papaya",
                                              "Permafrost",
                                              "Pineapple",
                                              "Pineapple Diesel",
                                              "Pineapple Express",
                                              "Pineapple Kush",
                                              "Pineapple Thai",
                                              "Pineapple Trainwreck",
                                              "Pink Kush",
                                              "Pink Pez",
                                              "Pitbull",
                                              "Platinum Bubba",
                                              "Platinum Bubba Kush",
                                              "Platinum Girl Scout Cookies",
                                              "Platinum Kush",
                                              "Platinum OG",
                                              "Platinum Purple Kush",
                                              "Pluto Kush",
                                              "Poison Haze",
                                              "Popcorn Kush",
                                              "Pot of Gold",
                                              "Power Kush",
                                              "Power Plant",
                                              "Pre-98 Bubba Kush",
                                              "Presidential OG",
                                              "Pure Afghan",
                                              "Pure Kush",
                                              "Pure OG",
                                              "Pure Power Plant",
                                              "Purple Afghani",
                                              "Purple AK-47",
                                              "Purple Arrow",
                                              "Purple Berry",
                                              "Purple Buddha",
                                              "Purple Candy",
                                              "Purple Cream",
                                              "Purple Diesel",
                                              "Purple Dragon",
                                              "Purple Dream",
                                              "Purple Goo",
                                              "Purple Hashplant",
                                              "Purple Haze",
                                              "Purple Ice",
                                              "Purple Kush",
                                              "Purple Mr. Nice",
                                              "Purple Nepal",
                                              "Purple OG Kush",
                                              "Purple Passion",
                                              "Purple Princess",
                                              "Purple Sage ",
                                              "Purple Skunk",
                                              "Purple Sour Diesel",
                                              "Purple Tonic",
                                              "Purple Trainwreck",
                                              "Purple Urkle",
                                              "Purple Voodoo",
                                              "Purple Wreck",
                                              "PVC OG",
                                              "Q3",
                                              "Qleaner",
                                              "Qrazy Train",
                                              "Quebec Gold",
                                              "Querkle",
                                              "Rainbow",
                                              "Raskal OG",
                                              "Raspberry Kush",
                                              "Recon",
                                              "Red Dragon",
                                              "Red Dwarf",
                                              "Red Haze",
                                              "Redwood Kush",
                                              "Richie Rich",
                                              "Rocklock",
                                              "Romping Goddess",
                                              "Romulan",
                                              "Romulan Grapefruit",
                                              "Root Beer Kush",
                                              "Russian Rocket Fuel",
                                              "SAGE",
                                              "Sage N Sour",
                                              "Satori",
                                              "Seattle Blue",
                                              "Sensi Star",
                                              "SFV OG",
                                              "Shaman",
                                              "Shark Shock",
                                              "Sharksbreath",
                                              "Shipwreck",
                                              "Shishkaberry",
                                              "Shiva Skunk",
                                              "Shoreline",
                                              "Sierra Mist",
                                              "Silver Haze",
                                              "Silver Pearl",
                                              "Silver Surfer",
                                              "Silverback Gorilla",
                                              "Skunk #1",
                                              "Skunky Diesel",
                                              "Skydog",
                                              "Skywalker",
                                              "Skywalker OG",
                                              "Snoop\u0027s Dream",
                                              "Snow White",
                                              "Snowcap",
                                              "Soul Shine",
                                              "Sour Apple",
                                              "Sour Cheese",
                                              "Sour Chocolate",
                                              "Sour Diesel",
                                              "Sour Dream",
                                              "Sour Flower",
                                              "Sour Grape",
                                              "Sour Grapes",
                                              "Sour Haze",
                                              "Sour Kush",
                                              "Sour OG",
                                              "Sour Power",
                                              "Sour Tsunami",
                                              "Space Bomb",
                                              "Space Dawg",
                                              "Space Queen",
                                              "Starry Night",
                                              "Stevie Wonder",
                                              "Strawberry",
                                              "Strawberry Cough",
                                              "Strawberry Diesel",
                                              "Strawberry Dream",
                                              "Strawberry Kush",
                                              "Sugar Shack",
                                              "Super Blue Dream",
                                              "Super Cat Piss",
                                              "Super Green Crack",
                                              "Super Kush",
                                              "Super Lemon Haze",
                                              "Super Silver Haze",
                                              "Super Skunk",
                                              "Super Sour Diesel",
                                              "Super Sour Widow",
                                              "Superman OG",
                                              "Sweet Diesel",
                                              "Sweet Island Skunk",
                                              "Sweet Kush",
                                              "Sweet Tooth",
                                              "Swiss Bliss",
                                              "Tahoe OG",
                                              "Taliban Poison",
                                              "Tangerine Dream",
                                              "Tangerine Kush",
                                              "Tangie",
                                              "Thai Haze",
                                              "Thai-Tanic",
                                              "Thaidal Wave",
                                              "THC Bomb",
                                              "The Flav",
                                              "The Void",
                                              "The White",
                                              "Thin Mint",
                                              "Tiger Woods",
                                              "Trainwreck",
                                              "Trident",
                                              "Trifecta",
                                              "Trinity",
                                              "Triple Diesel",
                                              "Tropical Tang",
                                              "Tropicali",
                                              "True OG",
                                              "UK Cheese",
                                  "Ultimate Trainwreck",
                                              "UW",
                                              "Vanilla Kush",
                                              "Venice OG",
                                              "Verde Electric",
                                              "Very Berry Haze",
                                              "Violator Kush",
                                              "Voodoo",
                                              "Vortex",
                                              "Waipi\u0027o Hapa",
                                              "Waldo",
                                              "Walrus Kush",
                                              "Warlock",
                                              "White Berry",
                                              "White Dawg",
                                              "White Kush",
                                              "White Queen",
                                              "White Rhino",
                                              "White Russian",
                                              "White Shark",
                                              "White Widow",
                                              "White Zombie",
                                              "Willie Nelson",
                                              "Willy\u0027s Wonder",
                                              "Wonder Haze",
                                              "Wonder Woman",
                                              "Wonder Woman OG",
                                              "Wonka\u0027s Bubblicious",
                                              "Woody Kush",
                                              "XJ-13",
                                              "XXX 420",
                                              "Yoda OG",
                                              "Yumboldt",
                                              "Zombie OG"
                                                               
]